### ISSUE TITLE
在游戏中添加该模组会无法启动，请`readme`中添加依赖列表

### ISSUE THREAD

**Issue by pizeroLOL** [KELETU66666/keletupack#6]
[minecraft-exported-logs-2022-05-30T18-54-54.log](https://github.com/KELETU66666/keletupack/files/8797759/minecraft-exported-logs-2022-05-30T18-54-54.log)

**Comment by KELETU66666** [comment]
你来吧

**Comment by pizeroLOL** [comment]
别急着关issue啊，我不知道依赖啊

**Comment by pizeroLOL** [comment]
@KELETU66666 我tm不知道啊

**Comment by pizeroLOL** [comment]
而且pr可以合并到issue的
